/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#abc7ff",
        "on-error-container": "#93000a",
        "surface-bright": "#f9f9fb",
        "on-tertiary-fixed-variant": "#004e59",
        "on-primary-fixed-variant": "#00458f",
        "on-error": "#ffffff",
        "on-secondary-container": "#636264",
        "secondary": "#5f5e60",
        "primary-container": "#0071e3",
        "on-surface-variant": "#414753",
        "surface-container-high": "#e8e8ea",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#e2dfe1",
        "on-background": "#1a1c1d",
        "on-tertiary": "#ffffff",
        "tertiary": "#006573",
        "inverse-on-surface": "#f0f0f2",
        "on-secondary-fixed": "#1b1b1d",
        "surface-variant": "#e2e2e4",
        "surface-tint": "#005cbb",
        "inverse-surface": "#2f3132",
        "surface-dim": "#d9dadc",
        "on-primary": "#ffffff",
        "outline": "#717785",
        "on-tertiary-container": "#f6fdff",
        "on-primary-fixed": "#001b3f",
        "error": "#ba1a1a",
        "tertiary-fixed": "#a1efff",
        "on-secondary-fixed-variant": "#474649",
        "background": "#f9f9fb",
        "surface": "#f9f9fb",
        "on-secondary": "#ffffff",
        "primary": "#0059b5",
        "surface-container": "#eeeef0",
        "surface-container-highest": "#e2e2e4",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#c8c6c8",
        "on-surface": "#1a1c1d",
        "tertiary-container": "#008091",
        "primary-fixed": "#d7e2ff",
        "secondary-fixed": "#e4e2e4",
        "inverse-primary": "#abc7ff",
        "tertiary-fixed-dim": "#44d8f1",
        "outline-variant": "#c1c6d6",
        "surface-container-low": "#f3f3f5",
        "on-tertiary-fixed": "#001f25",
        "on-primary-container": "#fcfbff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1.5rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Inter", "SF Pro", "sans-serif"],
        "body": ["Inter", "SF Pro", "sans-serif"],
        "label": ["Inter", "SF Pro", "sans-serif"]
      }
    },
  },
  plugins: [],
}
